### PR TITLE
My bad, ZwUnloadDriver has to be called before RegDeleteKey

### PR DESCRIPTION
**Pull request by BerkanYildiz**
Again, sorry 🙆‍♂️

### CODE REVIEW

**Comment by BerkanYildiz** [comment]
Wrongly pasted it from my source :kappa:

image

**Comment by NotAdam** [comment]
why aren't you checking the return code properly and only removing the key if the unload is successful?

**Comment by BerkanYildiz** [comment]
Assumed Capcom would never fail unloading. Will add the check in PR. Thanks for pointing this out :d

**Comment by not-wlan** [comment]
Merged!

**Pull request merged**
